name = "Call Julia from Python experiments"
authors = ["Abel Soares Siqueira"]

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
Colors = "0.12.8"
Parsers = "2.1.0"
PyCall = "1.92.5"
UnicodePlots = "2.4.6"
julia = "1.6.4"
